    var config0 = liquidFillGaugeDefaultSettings();
    config0.displayPercent = false;
    config0.maxValue = 40;
    config0.waveAnimateTime = 800;
    var gauge1 = loadLiquidFillGauge("fillgauge1", 28, config0);
    var config1 = liquidFillGaugeDefaultSettings();
    config1.circleColor = "#55CCCC";
    config1.textColor = "#44CCCC";
    config1.waveTextColor = "#22AAAA";
    config1.waveColor = "#77EEEE";
    config1.circleThickness = 0.2;
    config1.textVertPosition = 0.2;
    config1.waveAnimateTime = 1000;
    config1.displayPercent = false;
    config1.maxValue = 45;
    var gauge2= loadLiquidFillGauge("fillgauge2", 28, config1);
    var config2 = liquidFillGaugeDefaultSettings();
    config2.circleColor =   "#5588CC";
    config2.textColor =     "#4488CC";
    config2.waveTextColor = "#2299AA";
    config2.waveColor =     "#77BBEE";
    config2.circleThickness = 0.1;
    config2.circleFillGap = 0.2;
    config2.textVertPosition = 0.8;
    config2.waveAnimateTime = 2000;
    config2.waveHeight = 0.3;
    config2.waveCount = 1;
    config2.displayPercent = false;
    var gauge3 = loadLiquidFillGauge("fillgauge3", 63, config2);
    var config3 = liquidFillGaugeDefaultSettings();
    config3.textVertPosition = 0.8;
    config3.waveAnimateTime = 6500;
    config3.waveHeight = 0.25;
    config3.waveAnimate = true;
    config3.waveOffset = 0.25;
    config3.valueCountUp = false;
    config3.displayPercent = false;
    config3.maxValue = 30;
    var gauge4 = loadLiquidFillGauge("fillgauge4", 21, config3);
    var config4 = liquidFillGaugeDefaultSettings();
    config4.circleColor =   "#3388CC";
    config4.textColor =     "#2288CC";
    config4.waveTextColor = "#1199AA";
    config4.waveColor =     "#66BBAA";
    config4.textVertPosition = 0.8;
    config4.waveAnimateTime = 1000;
    config4.waveHeight = 0.05;
    config4.waveAnimate = true;
    config4.waveRise = false;
    config4.waveHeightScaling = false;
    config4.waveOffset = 0.25;
    config4.textSize = 0.75;
    config4.waveCount = 3;
    config4.displayPercent = false;
    config4.maxValue = 40;
    var gauge5 = loadLiquidFillGauge("fillgauge5", 23, config4);
    var config5 = liquidFillGaugeDefaultSettings();
    config5.circleThickness = 0.20;
    config5.circleColor =   "#44CCBB";
    config5.textColor =     "#008899";
    config5.waveTextColor = "#22AAAA";
    config5.waveColor =     "#66EEAA";
    config5.textVertPosition = 0.52;
    config5.waveAnimateTime = 5000;
    config5.waveHeight = 0;
    config5.waveAnimate = false;
    config5.waveCount = 2;
    config5.waveOffset = 0.25;
    config5.textSize = 1.2;
    config5.minValue = 1;
    config5.maxValue = 30;
    config5.displayPercent = false;
    var gauge6 = loadLiquidFillGauge("fillgauge6", 14, config5);

    function NewValue(){
        if(Math.random() > .5){
            return Math.round(Math.random()*100);
        } else {
            return (Math.random()*100).toFixed(1);
        }
    }